config/routes.rb
Rails.application.routes.draw do
  resources :cohorts, only: [:show, :edit, :update]
  resources :users, only: [:new, :create]
  resources :blogs, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :students, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/student/:id/home', to: 'students#home', as: 'home_student'

  get '/tcf/:id/home', to: 'tcfs#home', as: 'home_tcf'

  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

  def new_line
    arr = self.content.split("\n")
  end
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :cohort
  has_many :blogs

  validates :name, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :status

  def status
    @logged_in = !!session[:user_id]
    @logged_in_user = User.find(session[:user_id]) if @logged_in
  end

  def login_user(user)
    session[:user_id] = user.id
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :get_blog, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def show
  end

  def new
    @blog = Blog.new
    @students = @logged_in_user.cohort.users.where(role: 'Student')
  end

  def create
    @blog = Blog.create(blog_params)
    if @logged_in_user.role == 'TCF'
      redirect_to home_tcf_path(@logged_in_user)
    else
      redirect_to @blog
    end
  end

  def edit
    if session[:user_id] = @blog.user_id
      @blog
    else
      flash[:errors] = "Login to edit your blog"
      redirect_to login_path
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog
    else
      flash[:errors] = @blog.errors.full_messages
      redirect_to edit_blog_path
    end
  end

  def destroy
    if session[:user_id] == @logged_in_user.id
      @blog.delete
      redirect_to home_student_path(@logged_in_user)
    end
  end

  private

  def get_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :due_date, :user_id)
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  before_action :get_cohort, only: [:show, :edit, :update]

  def show
    @tcfs = @cohort.users.where(role: 'TCF')
    @students = @cohort.users.where(role: 'Student')
  end

  def new

  end

  def create
  end

  def edit
    unless @logged_in_user.role == 'TCF' && @logged_in_user.cohort.id == @cohort.id
      flash[:errors] = ['Not authorized to make changes']
      redirect_to @cohort
    end
  end

  def update
    @cohort.update(cohort_params)
    redirect_to @cohort
  end

  private

  def get_cohort
    @cohort = Cohort.find(params[:id])
  end

  def cohort_params
    params.require(:cohort).permit(:name, :mod)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    if @logged_in
      if @logged_in_user.role == "TCF"
        redirect_to home_tcf_path(@logged_in_user)
      else
        redirect_to student_tcf_path(@logged_in_user)
      end
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      login_user(@user)
      if @user.role == 'TCF'
        redirect_to home_tcf_path(@user)
      else
        redirect_to home_student_path(@user)
      end
    else
      flash[:errors] = ['Incorrect username or password']
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :get_user, only: [:home, :show, :edit, :update]

  def home
    if session[:user_id] == @user.id
      @tcfs = @user.cohort.users.where(role: 'TCF')
      @students = @user.cohort.users.where(role: 'Student')
      @blogs = @user.blogs
    else session[:user_id] == nil
      flash[:errors] = ['Login to view profile homepage']
      redirect_to login_path
    end
  end

  def show
  end

  def edit
    @cohorts = Cohort.all
    unless @logged_in_user.role == 'TCF' && @logged_in_user.cohort == @user.cohort
      redirect_to home_tcf_path(@logged_in_user)
    end
  end

  def update
    @user.update(student_params)
    redirect_to home_tcf_path(@logged_in_user)
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:cohort_id)
  end
end

app/controllers/tcfs_controller.rb
class TcfsController < ApplicationController

  before_action :get_user, only: [:home]

  def home
    if session[:user_id] == @user.id
      @students = @user.cohort.users.where(role: 'Student')
    else session[:user_id] == nil
      flash[:errors] = ['Login to view profile homepage']
      redirect_to login_path
    end
  end

  private

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
    @cohorts = Cohort.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      if @user.role == 'TCF'
        redirect_to home_tcf_path(@user)
      else
        redirect_to home_student_path(@user)
      end
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :role, :cohort_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Blog Form</h1>
          <% if @blog.title == nil %>
          <h5>Due by:
            <i><%= @blog.due_date %></i>
            <h5>
              <% end %>
              <hr>
              <div class="form-group">
                <form action="/blogs/<%= @blog.id %>" ,="," method='post'>
                  <input type="hidden" name="_method" value='patch'>
                  <label for="title">Title</label>
                  <input type="text" id="title" class="form-control" name="blog[title]" placeholder="Title" value="<%= @blog.title %>" required="required"><br>
                  <label for="content">Blog</label>
                  <textarea class="form-control" rows="10" id="content" name="blog[content]" placeholder="Write your blog here" required="required"><%= @blog.content %></textarea><br>
                  <input type="hidden" id="user_id" name="blog[user_id]" value="<%= @logged_in_user.id %>">
                  <button class="btn btn-lg btn-primary btn-block basic-font" type="submit">Post Blog</button>
                </form>
              </div>
        </div>
      </div>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/blogs/new.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <% if @logged_in_user.role == 'TCF' %>
      <div class="row">
        <div class="col-md-12">
          <h1>Assign Blog</h1>
          <hr>
          <%= form_for(@blog) do |f| %>
          <%= f.label :student%>:
          <%= f.collection_select(:user_id, @students, :id, :name) %>
          <br><br>
          <%= f.label :due_date %>:
          <%= f.text_field :due_date, placeholder: 'MM/DD/YY' %>
          <br><br>
          <button class="btn btn-lg btn-primary btn-block basic-font" type="submit">Assign Blog</button>
          <% end %>
        </div>
      </div>
      <% else %>
      <div class="row">
        <div class="col-md-12">
          <h1>New Blog</h1>
          <hr>
          <div class="form-group">
            <form action='/blogs' ,="," method='post'>
              <label for="title">Title</label>
              <input type="text" id="title" class="form-control" name="blog[title]" placeholder="Title" required="required"><br>
              <label for="content">Blog</label>
              <textarea class="form-control" rows="10" id="content" name="blog[content]" placeholder="Write your blog here" required="required"></textarea><br>
              <label for="due_date">Today's Date</label>
              <input type="text" id="due_date" class="form-control" name="blog[due_date]" placeholder="MM/DD/YY" required="required"><br>
              <input type="hidden" id="user_id" name="blog[user_id]" value="<%= @logged_in_user.id %>" %="%">
              <button class="btn btn-lg btn-primary btn-block basic-font" type="submit">Post Blog</button>
            </form>
          </div>
        </div>
      </div>
      <% end %>
      <br>
      <hr>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/blogs/show.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1><%= @blog.title %></h1>
          <% if @blog.user.id == session[:user_id] %>
          <h3><i>By: Me</i></h3>
          <% else %>
          <h3><i>By: <%= @blog.user.name %></i></h3>
          <% end %>
          <hr>
          <% @blog.new_line.each do |paragraph| %>
          <p><%= paragraph %></p>
          <% end %>
          <% if @blog.user.id == session[:user_id] %>
          <a class="font-flatiron btn btn-secondary" href="/blogs/<%= @blog.id %>/edit" role="button">Edit Blog &raquo;</a>
          <a class="font-flatiron btn btn-secondary" href="/blogs/<%= @blog.id %>" data-method='delete' role="button" onclick="return confirm('Delete this post?')">Delete Blog &raquo;</a>
          <% end %>
          <hr>
          <% unless @blog.user.id == session[:user_id] %>
          <i>Read more blogs from, <%= link_to @blog.user.name, student_path(@blog.user) %></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/cohorts/edit.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <% if @logged_in_user.role == 'TCF' %>
      <div class="row">
        <div class="col-md-12">
          <h1>Edit Cohort <i><%= @cohort.name %></i></h1>
          <hr>
          <%= form_for(@cohort) do |f| %>
          <%= f.label :name %>:
          <%= f.text_field :name, placeholder: 'Name' %>
          <br><br>
          <%= f.label :mod %>:
          <%= f.select :mod, (1..5), disabled: @cohort.mod %>
          <br><br>
          <button class="btn btn-lg btn-primary btn-block basic-font" type="submit">Update <i><%= @cohort.name %></i></button>
          <% end %>
        </div>
      </div>
      <% end %>
      <br>
      <hr>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/cohorts/show.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1><%= @cohort.name %></h1>
          <h3><i>Mod <%= @cohort.mod %></i></h3>
          <hr>
          <h1>TCF</h1>
          <% @tcfs.each do |tcf| %>
          <% if tcf.id == @logged_in_user.id %>
          <h3><%= tcf.name %> <i>(Me)</i></h3>
          <% else %>
          <h3><%= tcf.name %></h3>
          <% end %>
          <% end %>
          <% if @logged_in_user.role == 'TCF' %>
          <hr>
          <h1>Edit Cohort</h1>
          <a class="font-flatiron btn btn-secondary" href="/cohorts/<%= @cohort.id %>/edit" role="button">Edit <i><%= @cohort.name %></i> &raquo;</a><br><br>
          <% end %>
        </div>
        <div class="col-md-6">
          <h1>Students</h1>
          <% @students.each do |student| %>
          <% if @logged_in_user.role == 'Student' && @logged_in_user.id == student.id %>
          <a class="font-flatiron btn btn-secondary" href="/student/<%= student.id %>/home" role="button"><%= student.name %> <i>(Me)</i> &raquo;</a><br><br>
          <% else %>
          <a class="font-flatiron btn btn-secondary" href="/students/<%= student.id %>/" role="button"><%= student.name %> &raquo;</a><br><br>
          <% end %>
          <% end %>
        </div>
      </div>
      <hr>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2FlatironBlogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="sticky-footer.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Flatiron Blogger</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% unless @logged_in %>
        <div class="collapse navbar-collapse" id="navbarsExample02">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Login', login_path %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Signup', new_user_path %>
            </li>
          </ul>
        </div>
      <% else %>
          <div class="collapse navbar-collapse" id="navbarsExample02">
            <ul class="navbar-nav mr-auto">
              <% if @logged_in_user.role == 'TCF' %>
                <li class="nav-item active">
                  <%= link_to "#{@logged_in_user.name}", home_tcf_path(@logged_in_user) %>
                </li>
                <li class="nav-item active">
                  <%= link_to 'Signout', signout_path, method: :delete %>
                </li>
              <% else %>
                <li class="nav-item active">
                  <%= link_to "#{@logged_in_user.name}", home_student_path(@logged_in_user)%>
                </li>
                <li class="nav-item active">
                  <%= link_to 'Signout', signout_path, method: :delete %>
                </li>
              <% end  %>
            <% end %>
            </ul>
          </div>
        </nav>
        <img class="mb-4 center" src="https://upload.wikimedia.org/wikipedia/commons/6/6f/Flatiron-School-Horizontal-Blue-grey.png">
    <div class="basic-font text-center">
    <%= yield %>
    </div>
  </body>
</html>

app/views/students/edit.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Move Student</h1>
          <h3>Change <i><%= @user.name %>'s</i> Mod</h3>
          <hr><br>
          <div class="form-group">
            <%= form_for @user, as: :student, method: 'PATCH', url: "/students/#{@user.id}" do |f| %>
            <%= f.label :cohort %>:
            <%= f.collection_select(:cohort_id, @cohorts, :id, :name, disabled: @user.cohort.id) %>
            <br><br>
            <%= f.submit "Move #{@user.name}",:class => "btn btn-lg btn-primary btn-block basic-font", data: {confirm: "Move #{@user.name}?"}%>
            <% end %>
          </div>
        </div>
      </div>
      <br>
      <hr>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/students/home.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h1>Welcome, <%= @user.name %>!</h1>
          <hr>
          <h2>My Mod</h2>
          <h4><%= link_to @user.cohort.name, @user.cohort %> <i>(Mod <%= @user.cohort.mod %>)</i></h4>
          <hr>
          <h2>My TCFs</h2>
          <% @tcfs.each do |tcf| %>
          <h4><%= tcf.name %></h4>
          <% end %>
          <hr>
          <h2>Blogs Due</h2>
          <% @blogs.each do |blog| %>
          <% if blog.title == nil %>
          <a class="font-flatiron btn btn-secondary" href="/blogs/<%= blog.id %>/edit" role="button"><%= blog.due_date %> &raquo;</a><br><br>
          <% end %>
          <% end %>
        </div>

        <div class="col-md-4">
          <h2>My Modmates</h2>
          <% @students.each do |student| %>
          <% unless student.id == session[:user_id] %>
          <a class="font-flatiron btn btn-secondary" href="/students/<%= student.id %>" role="button"><%= student.name %> &raquo;</a><br><br>
          <% end %>
          <% end %>
        </div>

        <div class="col-md-4">
          <h2>My Blogs</h2>
          <% @blogs.each do |blog| %>
          <% if blog.title != nil %>
          <a class="font-flatiron btn btn-secondary" href="/blogs/<%= blog.id %>" role="button"><%= blog.title %> &raquo;</a><br><br>
          <% end %>
          <% end %>
          <hr><br>
          <h2>Post Blog</h2>
          <a class="font-flatiron btn btn-secondary" href="/blogs/new" role="button">Post Blog &raquo;</a><br>
        </div>
      </div>
      <hr>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/students/show.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1><%= @user.name %>'s Page!</h1>
          <h3><%= @user.cohort.name %> <i>(Mod <%= @user.cohort.mod %>)</i></h3>
          <hr>
          <h3><%= @user.name %>'s Blogs</h3>
          <% @user.blogs.each do |blog|%>
          <% unless blog.title == nil %>
          <a class="font-flatiron btn btn-secondary" href="/blogs/<%= blog.id %>" role="button"><%= blog.title %> &raquo;</a><br><br>
          <% end %>
          <% end %>
        </div>
        <hr>
      </div>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>

app/views/tcfs/home.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>Welcome, <%= @user.name %>!</h1>
          <hr>
          <h2>My Mod</h2>
          <h4><%= link_to @user.cohort.name, @user.cohort %> <i>(Mod <%= @user.cohort.mod %>)</i></h4>
          <hr>
          <h2>Assign Blog</h2>
          <a class="font-flatiron btn btn-secondary" href="/blogs/new" role="button">Assign Blog &raquo;</a><br>
          <hr>
          <h2>Blogs Due</h2>

          <% @students.each do |student| %>
          <% student.blogs.each do |blog| %>
          <% if blog.title == nil && blog.due_date.present? %>
          <%= student.name %>, <i><%= blog.due_date %></i><br>
          <% break %>
          <% end %>
          <% end %>
          <% end %>
        </div>

        <div class="col-md-6">
          <h2>My Students</h2>
          <% @students.each do |student| %>
          <%= link_to student.name, student_path(student) %><br>
          <a class="font-flatiron btn btn-secondary" href="/students/<%= student.id %>/edit" role="button">Move <%= student.name %> &raquo;</a><br><br>
          <% end %>
        </div>
      </div>
      <hr>
    </div>
  </div>
</main>

<footer class="container">
  <p>&copy; Flatiron Blogger 2019-2019</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>

</html>